
import { MuscleGroup, Exercise, CombatSpecialty, RankArchetype, ExerciseMetric, Title } from './types';

export const MOTIVATIONAL_PUSH_MESSAGES = [
  "💀 Nadie va a entrenar por ti. Levántate.",
  "🔥 Si hoy no duele, mañana no creces.",
  "⚔️ Estás a una rutina de ser mejor que ayer.",
  "😤 Muévete. La pereza no construye cuerpos fuertes.",
  "🏆 ¿Quieres resultados o excusas? Decide.",
  "💪 Entrena como si tuvieras algo que demostrar.",
  "🧠 Tu mente se rinde antes que tu cuerpo. Sigue.",
  "🚀 Cada repetición te acerca a tu mejor versión.",
  "⚡ Hoy entrenas. Mañana agradeces.",
  "🔥 Nadie recuerda a los débiles.",
  "🏋️ Hazlo aunque no tengas ganas.",
  "😈 La disciplina vence a la motivación.",
  "🩸 Si no sudas, no cuenta.",
  "🧱 Construye el cuerpo que tu mente sueña.",
  "⚔️ Hoy se entrena. Punto."
];

export const TITLES_DATABASE: Title[] = [
  // --- FUERZA (Línea Dragón y Titán - 20) ---
  { id: 'f-01', name: 'Bebé Dragón', icon: 'fa-egg', color: '#94a3b8', category: 'Fuerza', description: 'El inicio de una leyenda. Empuje inicial superado.', requirement: { type: 'exercise_weight', exerciseName: 'Press banca plano', value: 55 } },
  { id: 'f-02', name: 'Dragón Joven', icon: 'fa-dragon', color: '#cbd5e1', category: 'Fuerza', description: 'Tus alas empiezan a cargar peso real.', requirement: { type: 'exercise_weight', exerciseName: 'Press banca plano', value: 80 } },
  { id: 'f-03', name: 'Dragón de Escamas de Acero', icon: 'fa-shield-halved', color: '#64748b', category: 'Fuerza', description: 'Tu pecho es una armadura impenetrable.', requirement: { type: 'exercise_weight', exerciseName: 'Press banca plano', value: 100 } },
  { id: 'f-04', name: 'Dragón Alfa', icon: 'fa-fire-dragon', color: '#ef4444', category: 'Fuerza', description: 'Llamas de fuerza pura brotan de tus empujes.', requirement: { type: 'exercise_weight', exerciseName: 'Press banca plano', value: 120 } },
  { id: 'f-05', name: 'Dragón Ancestral', icon: 'fa-khanda', color: '#fbbf24', category: 'Fuerza', description: 'Fuerza divina que trasciende generaciones.', requirement: { type: 'exercise_weight', exerciseName: 'Press banca plano', value: 140 } },
  { id: 'f-06', name: 'Cachorro de Fenrir', icon: 'fa-dog', color: '#94a3b8', category: 'Fuerza', description: 'Tus primeros pasos en el peso muerto.', requirement: { type: 'exercise_weight', exerciseName: 'Peso muerto', value: 100 } },
  { id: 'f-07', name: 'Lobo del Abismo', icon: 'fa-wolf-pack-white', color: '#475569', category: 'Fuerza', description: 'Tracción sombría y poderosa.', requirement: { type: 'exercise_weight', exerciseName: 'Peso muerto', value: 140 } },
  { id: 'f-08', name: 'Devorador de Tierras', icon: 'fa-mountain-sun', color: '#ea580c', category: 'Fuerza', description: 'La tierra tiembla cuando tiras de la barra.', requirement: { type: 'exercise_weight', exerciseName: 'Peso muerto', value: 180 } },
  { id: 'f-09', name: 'Fenrir Desatado', icon: 'fa-skull-crossbones', color: '#1e293b', category: 'Fuerza', description: 'Fuerza bruta que rompe cualquier cadena.', requirement: { type: 'exercise_weight', exerciseName: 'Peso muerto', value: 220 } },
  { id: 'f-10', name: 'Titán de los Cimientos', icon: 'fa-columns', color: '#94a3b8', category: 'Fuerza', description: 'Sentadilla base establecida.', requirement: { type: 'exercise_weight', exerciseName: 'Sentadilla', value: 100 } },
  { id: 'f-11', name: 'Pilar de Hierro', icon: 'fa-building', color: '#cbd5e1', category: 'Fuerza', description: 'Tus piernas sostienen el mundo.', requirement: { type: 'exercise_weight', exerciseName: 'Sentadilla', value: 140 } },
  { id: 'f-12', name: 'Coloso de Rodas', icon: 'fa-monument', color: '#fbbf24', category: 'Fuerza', description: 'Arquitectura humana perfecta en carga.', requirement: { type: 'exercise_weight', exerciseName: 'Sentadilla', value: 180 } },
  { id: 'f-13', name: 'Atlas Eterno', icon: 'fa-globe-americas', color: '#3b82f6', category: 'Fuerza', description: 'Cargas el peso de la existencia en tus hombros.', requirement: { type: 'exercise_weight', exerciseName: 'Sentadilla', value: 210 } },
  { id: 'f-14', name: 'Sargento de Acero', icon: 'fa-medal', color: '#94a3b8', category: 'Fuerza', description: 'Dominio del press militar básico.', requirement: { type: 'exercise_weight', exerciseName: 'Press militar', value: 50 } },
  { id: 'f-15', name: 'General de la Arena', icon: 'fa-star-half-stroke', color: '#cbd5e1', category: 'Fuerza', description: 'Hombros de piedra forjados en batalla.', requirement: { type: 'exercise_weight', exerciseName: 'Press militar', value: 70 } },
  { id: 'f-16', name: 'Señor de la Guerra', icon: 'fa-crown', color: '#fbbf24', category: 'Fuerza', description: 'Tu autoridad en empuje vertical es absoluta.', requirement: { type: 'exercise_weight', exerciseName: 'Press militar', value: 90 } },
  { id: 'f-17', name: 'Mazo de Guerra', icon: 'fa-hammer', color: '#94a3b8', category: 'Fuerza', description: 'Curl de bíceps con potencia explosiva.', requirement: { type: 'exercise_weight', exerciseName: 'Curl con barra', value: 40 } },
  { id: 'f-18', name: 'Martillo Cósmico', icon: 'fa-meteor', color: '#a855f7', category: 'Fuerza', description: 'Fuerza centrífuga de nivel galáctico.', requirement: { type: 'exercise_weight', exerciseName: 'Curl con barra', value: 60 } },
  { id: 'f-19', name: 'Arquitecto del Caos', icon: 'fa-compass-drafting', color: '#6366f1', category: 'Fuerza', description: 'Más de 50 toneladas movidas históricamente.', requirement: { type: 'volume_total', value: 50000 } },
  { id: 'f-20', name: 'Avatar de la Destrucción', icon: 'fa-eye-evil', color: '#721c24', category: 'Fuerza', description: 'El pináculo del poder destructivo en GYM/G.', requirement: { type: 'sum_big_three', value: 500 } },

  // --- CONSTANCIA (Línea Monje y Máquina - 15) ---
  { id: 'c-01', name: 'Iniciado del Templo', icon: 'fa-om', color: '#94a3b8', category: 'Constancia', description: '10 días de racha. La disciplina germina.', requirement: { type: 'streak', value: 10 } },
  { id: 'c-02', name: 'Monje de Hierro', icon: 'fa-peace', color: '#cbd5e1', category: 'Constancia', description: '20 días. Tu mente domina al cuerpo.', requirement: { type: 'streak', value: 20 } },
  { id: 'c-03', name: 'Guardián del Hábito', icon: 'fa-shield-heart', color: '#fbbf24', category: 'Constancia', description: '50 días. El entrenamiento es tu religión.', requirement: { type: 'streak', value: 50 } },
  { id: 'c-04', name: 'Maestro Zen', icon: 'fa-yin-yang', color: '#ffffff', category: 'Constancia', description: '100 días. Paz absoluta entre pesas.', requirement: { type: 'streak', value: 100 } },
  { id: 'c-05', name: 'Circuito Activo', icon: 'fa-microchip', color: '#22d3ee', category: 'Constancia', description: '15 sesiones de entrenamiento.', requirement: { type: 'workouts_count', value: 15 } },
  { id: 'c-06', name: 'Protocolo de Batalla', icon: 'fa-file-code', color: '#3b82f6', category: 'Constancia', description: '50 sesiones. Algoritmo de fuerza perfeccionado.', requirement: { type: 'workouts_count', value: 50 } },
  { id: 'c-07', name: 'Unidad de Élite', icon: 'fa-user-gear', color: '#6366f1', category: 'Constancia', description: '100 sesiones. Eres una máquina de guerra.', requirement: { type: 'workouts_count', value: 100 } },
  { id: 'c-08', name: 'IA Suprema', icon: 'fa-brain', color: '#a855f7', category: 'Constancia', description: '200 sesiones. Tu sistema nunca falla.', requirement: { type: 'workouts_count', value: 200 } },
  { id: 'c-09', name: 'Eslabón de Platino', icon: 'fa-link', color: '#cbd5e1', category: 'Constancia', description: 'Racha inquebrantable de 3 meses.', requirement: { type: 'streak', value: 90 } },
  { id: 'c-10', name: 'Corazón de Relojería', icon: 'fa-clock', color: '#f59e0b', category: 'Constancia', description: 'Entrenas siempre a la misma hora.', requirement: { type: 'workouts_count', value: 75 } },
  { id: 'c-11', name: 'Soldado Eterno', icon: 'fa-person-military-pointing', color: '#166534', category: 'Constancia', description: 'Nunca has faltado una semana.', requirement: { type: 'streak', value: 30 } },
  { id: 'c-12', name: 'Espíritu de Samurái', icon: 'fa-torii-gate', color: '#dc2626', category: 'Constancia', description: 'Honor y sudor en cada repetición.', requirement: { type: 'workouts_count', value: 125 } },
  { id: 'c-13', name: 'Incombustible', icon: 'fa-fire-extinguisher', color: '#ea580c', category: 'Constancia', description: 'Superaste lesiones y fatiga.', requirement: { type: 'streak', value: 45 } },
  { id: 'c-14', name: 'Arquitecto del Destino', icon: 'fa-compass', color: '#334155', category: 'Constancia', description: 'Un año de compromiso absoluto.', requirement: { type: 'streak', value: 365 } },
  { id: 'c-15', name: 'Divino Constante', icon: 'fa-wand-magic-sparkles', color: '#fbbf24', category: 'Constancia', description: 'La constancia hecha deidad.', requirement: { type: 'workouts_count', value: 300 } },

  // --- CARDIO (Línea Viento y Mar - 10) ---
  { id: 'ca-01', name: 'Brisa Ligera', icon: 'fa-wind', color: '#94a3b8', category: 'Cardio', description: 'Tus pulmones despiertan.', requirement: { type: 'cardio_time_total', value: 1800 } },
  { id: 'ca-02', name: 'Corriente Marina', icon: 'fa-water', color: '#3b82f6', category: 'Cardio', description: 'Resistencia fluida y constante.', requirement: { type: 'cardio_time_total', value: 7200 } },
  { id: 'ca-03', name: 'Vendaval del Norte', icon: 'fa-fan', color: '#cbd5e1', category: 'Cardio', description: 'Rapidez que congela el tiempo.', requirement: { type: 'cardio_sessions', value: 10 } },
  { id: 'ca-04', name: 'Ola de Tsunami', icon: 'fa-house-tsunami', color: '#1d4ed8', category: 'Cardio', description: 'Potencia aeróbica imparable.', requirement: { type: 'cardio_time_total', value: 18000 } },
  { id: 'ca-05', name: 'Tornado de Fuego', icon: 'fa-tornado', color: '#ef4444', category: 'Cardio', description: 'Quemas el asfalto bajo tus pies.', requirement: { type: 'cardio_time_total', value: 36000 } },
  { id: 'ca-06', name: 'Nube de Tormenta', icon: 'fa-cloud-showers-heavy', color: '#475569', category: 'Cardio', description: 'Entrenas bajo cualquier condición.', requirement: { type: 'cardio_sessions', value: 30 } },
  { id: 'ca-07', name: 'Relámpago de Élite', icon: 'fa-bolt-lightning', color: '#fbbf24', category: 'Cardio', description: 'Velocidad de reacción sobrehumana.', requirement: { type: 'cardio_time_total', value: 72000 } },
  { id: 'ca-08', name: 'Huracán de Almas', icon: 'fa-hurricane', color: '#ea580c', category: 'Cardio', description: 'Tu pulso es una fuerza de la naturaleza.', requirement: { type: 'cardio_time_total', value: 100000 } },
  { id: 'ca-09', name: 'Guardián del Horizonte', icon: 'fa-mountain', color: '#166534', category: 'Cardio', description: 'Resistencia infinita de montaña.', requirement: { type: 'cardio_sessions', value: 100 } },
  { id: 'ca-10', name: 'Señor de los Vientos', icon: 'fa-cloud-bolt', color: '#ffffff', category: 'Cardio', description: 'Vuelas sobre la resistencia humana.', requirement: { type: 'cardio_time_total', value: 200000 } },

  // --- PROGRESIÓN (Línea Ascensión - 10) ---
  { id: 'p-01', name: 'Semilla de Guerrero', icon: 'fa-seedling', color: '#166534', category: 'Progreso', description: 'Nivel 10. La fuerza ha germinado.', requirement: { type: 'level', value: 10 } },
  { id: 'p-02', name: 'Brote de Titán', icon: 'fa-leaf', color: '#22c55e', category: 'Progreso', description: 'Nivel 20. Creciendo hacia la cima.', requirement: { type: 'level', value: 20 } },
  { id: 'p-03', name: 'Árbol de Hierro', icon: 'fa-tree', color: '#3f6212', category: 'Progreso', description: 'Nivel 30. Raíces profundas en el acero.', requirement: { type: 'level', value: 30 } },
  { id: 'p-04', name: 'Bosque Sagrado', icon: 'fa-mountain-city', color: '#fbbf24', category: 'Progreso', description: 'Nivel 40. Eres un ecosistema de poder.', requirement: { type: 'level', value: 40 } },
  { id: 'p-05', name: 'Cumbre Nevada', icon: 'fa-snowflake', color: '#ffffff', category: 'Progreso', description: 'Nivel 50. Pureza y altura máxima.', requirement: { type: 'level', value: 50 } },
  { id: 'p-06', name: 'Fénix Renacido', icon: 'fa-dove', color: '#dc2626', category: 'Progreso', description: 'Nivel 60. Siempre vuelves más fuerte.', requirement: { type: 'level', value: 60 } },
  { id: 'p-07', name: 'Nova Estelar', icon: 'fa-sun', color: '#fcd34d', category: 'Progreso', description: 'Nivel 70. Tu brillo es cegador.', requirement: { type: 'level', value: 70 } },
  { id: 'p-08', name: 'Agujero Negro', icon: 'fa-circle-dot', color: '#000000', category: 'Progreso', description: 'Nivel 80. Absorbes toda la carga.', requirement: { type: 'level', value: 80 } },
  { id: 'p-09', name: 'Galaxia de Fuerza', icon: 'fa-milky-way', color: '#a855f7', category: 'Progreso', description: 'Nivel 90. Infinito potencial.', requirement: { type: 'level', value: 90 } },
  { id: 'p-10', name: 'Dios Multiversal', icon: 'fa-gem', color: '#fbbf24', category: 'Progreso', description: 'Nivel 100. El fin del camino. La divinidad.', requirement: { type: 'level', value: 100 } },

  // --- SOCIAL (Línea Legión - 5) ---
  { id: 's-01', name: 'Voz del Pueblo', icon: 'fa-bullhorn', color: '#3b82f6', category: 'Social', description: 'Tu primer aliado en la arena.', requirement: { type: 'friends_count', value: 1 } },
  { id: 's-02', name: 'Líder de Escuadrón', icon: 'fa-people-group', color: '#6366f1', category: 'Social', description: '5 compañeros siguen tus pasos.', requirement: { type: 'friends_count', value: 5 } },
  { id: 's-03', name: 'Heraldo de la Victoria', icon: 'fa-flag-checkered', color: '#fbbf24', category: 'Social', description: 'Tu nombre es respetado por 10 guerreros.', requirement: { type: 'friends_count', value: 10 } },
  { id: 's-04', name: 'Emperador de la Red', icon: 'fa-city', color: '#721c24', category: 'Social', description: 'Controlas una legión de 20 activos.', requirement: { type: 'friends_count', value: 20 } },
  { id: 's-05', name: 'Leyenda de GYM/G', icon: 'fa-earth-europe', color: '#ffffff', category: 'Social', description: 'El mundo entero reconoce tu fuerza.', requirement: { type: 'friends_count', value: 50 } },
];

const INITIAL_PROGRESS = {
  nivel: 1,
  exp: 0,
  exp_necesaria: 55, 
  rango: 0,
  porcentaje: 0
};

export const EXERCISES_DATABASE: Exercise[] = [
  // --- CARDIO ---
  { id: 'cardio-01', name: 'Trotar', muscleGroup: MuscleGroup.CARDIO, description: 'Carrera de baja-media intensidad para resistencia aeróbica.', rankArchetype: RankArchetype.ENDURANCE, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'cardio-02', name: 'Caminadora', muscleGroup: MuscleGroup.CARDIO, description: 'Entrenamiento de marcha o carrera en cinta estática.', rankArchetype: RankArchetype.ENDURANCE, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'cardio-03', name: 'Nadar', muscleGroup: MuscleGroup.CARDIO, description: 'Resistencia total en medio acuático, bajo impacto articular.', rankArchetype: RankArchetype.ENDURANCE, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'cardio-04', name: 'Bicicleta', muscleGroup: MuscleGroup.CARDIO, description: 'Ciclismo estático o de ruta para potencia en piernas y cardio.', rankArchetype: RankArchetype.ENDURANCE, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },

  // --- PECHO ---
  { id: 'chest-01', name: 'Press banca plano', muscleGroup: MuscleGroup.PECHO, description: 'Básico fundamental para el empuje horizontal y desarrollo del pectoral mayor.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-02', name: 'Press banca inclinado', muscleGroup: MuscleGroup.PECHO, description: 'Enfoque en la porción clavicular del pectoral.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-03', name: 'Press banca declinado', muscleGroup: MuscleGroup.PECHO, description: 'Variante para enfatizar la porción inferior del pectoral.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-04', name: 'Aperturas con mancuernas planas', muscleGroup: MuscleGroup.PECHO, description: 'Aislamiento para estiramiento y contracción del pectoral en banco plano.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-05', name: 'Aperturas inclinadas', muscleGroup: MuscleGroup.PECHO, description: 'Enfoque de aislamiento en el pectoral superior.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-06', name: 'Aperturas en poleas', muscleGroup: MuscleGroup.PECHO, description: 'Tensión constante en todo el rango de movimiento pectoral.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-07', name: 'Fondos en paralelas', muscleGroup: MuscleGroup.PECHO, description: 'Potente constructor de la parte inferior del pecho y tríceps.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-08', name: 'Flexiones clásicas', muscleGroup: MuscleGroup.PECHO, description: 'Ejercicio base de empuje con peso corporal.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-09', name: 'Flexiones inclinadas', muscleGroup: MuscleGroup.PECHO, description: 'Facilita el movimiento enfocándose en la parte inferior del pecho.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-10', name: 'Flexiones declinadas', muscleGroup: MuscleGroup.PECHO, description: 'Aumenta la dificultad enfocándose en el pectoral superior.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-11', name: 'Press en máquina', muscleGroup: MuscleGroup.PECHO, description: 'Empuje controlado para máximo aislamiento y seguridad.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-12', name: 'Cruces en poleas', muscleGroup: MuscleGroup.PECHO, description: 'Trabajo de detalle y bombeo para la sección interna del pectoral.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-13', name: 'Press con agarre cerrado', muscleGroup: MuscleGroup.PECHO, description: 'Enfoque en tríceps y pectoral interno.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-14', name: 'Press con barra hexagonal', muscleGroup: MuscleGroup.PECHO, description: 'Agarre neutro para reducir estrés en hombros.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-15', name: 'Press unilateral con mancuerna', muscleGroup: MuscleGroup.PECHO, description: 'Mejora la estabilidad del core y corrige asimetrías pectorales.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-16', name: 'Pullover con mancuerna', muscleGroup: MuscleGroup.PECHO, description: 'Expansión torácica trabajando pecho y serratos.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-17', name: 'Pullover en polea', muscleGroup: MuscleGroup.PECHO, description: 'Tensión constante para serratos y pectoral inferior.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-18', name: 'Press isométrico', muscleGroup: MuscleGroup.PECHO, description: 'Máxima tensión en un punto fijo para reclutamiento de fibras.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'chest-19', name: 'Flexiones explosivas', muscleGroup: MuscleGroup.PECHO, description: 'Desarrollo de potencia de empuje pliométrica.', rankArchetype: RankArchetype.COMBAT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'chest-20', name: 'Flexiones diamante', muscleGroup: MuscleGroup.PECHO, description: 'Variante cerrada para tríceps y centro del pecho.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- ESPALDA & TRAPECIOS ---
  { id: 'pull-01', name: 'Dominadas', muscleGroup: MuscleGroup.ESPALDA, description: 'Ejercicio rey de autocarga para la amplitud dorsal.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-02', name: 'Jalón al pecho', muscleGroup: MuscleGroup.ESPALDA, description: 'Aislamiento vertical para el dorsal ancho en polea.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-03', name: 'Remo con barra', muscleGroup: MuscleGroup.ESPALDA, description: 'Básico de potencia para el grosor de la espalda.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-04', name: 'Remo con mancuernas', muscleGroup: MuscleGroup.ESPALDA, description: 'Permite un rango de movimiento unilateral más profundo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-05', name: 'Remo en máquina', muscleGroup: MuscleGroup.ESPALDA, description: 'Tracción horizontal asistida para máximo control muscular.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-06', name: 'Peso muerto', muscleGroup: MuscleGroup.ESPALDA, description: 'Fuerza absoluta, involucra toda la cadena posterior.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-07', name: 'Peso muerto rumano', muscleGroup: MuscleGroup.ESPALDA, description: 'Enfoque en isquiotibiales y zona lumbar bajo estiramiento.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-08', name: 'Jalón tras nuca', muscleGroup: MuscleGroup.ESPALDA, description: 'Variante de jalón para reclutamiento de fibras escapulares.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-09', name: 'Remo en polea baja', muscleGroup: MuscleGroup.ESPALDA, description: 'Tracción horizontal con tensión constante.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-10', name: 'Remo en T', muscleGroup: MuscleGroup.ESPALDA, description: 'Constructor de densidad en la espalda media.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-11', name: 'Pull-over en polea', muscleGroup: MuscleGroup.ESPALDA, description: 'Aislamiento dorsal puro mediante extensión de homblo.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-12', name: 'Superman', muscleGroup: MuscleGroup.ESPALDA, description: 'Fortalecimiento de la musculatura erectores espinales.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'pull-13', name: 'Buenos días', muscleGroup: MuscleGroup.ESPALDA, description: 'Bisagra de cadera para fortalecer lumbar e isquiotibiales.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-14', name: 'Dominadas agarre neutro', muscleGroup: MuscleGroup.ESPALDA, description: 'Variante más segura para hombros y excelente para braquial.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-15', name: 'Dominadas supinas', muscleGroup: MuscleGroup.ESPALDA, description: 'Enfoque híbrido en dorsal y bíceps.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-16', name: 'Remo unilateral en banco', muscleGroup: MuscleGroup.ESPALDA, description: 'Remo clásico con mancuerna apoyado para estabilidad.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-17', name: 'Jalón con agarre estrecho', muscleGroup: MuscleGroup.ESPALDA, description: 'Mayor énfasis en la parte inferior del dorsal y grosor.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-18', name: 'Remo invertido', muscleGroup: MuscleGroup.ESPALDA, description: 'Tracción horizontal con peso corporal.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-19', name: 'Peso muerto sumo', muscleGroup: MuscleGroup.ESPALDA, description: 'Variante de peso muerto con mayor implicación de aductores.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'pull-20', name: 'Hiperextensiones', muscleGroup: MuscleGroup.ESPALDA, description: 'Fortalecimiento directo de la zona lumbar y glúteos.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'trap-01', name: 'Encogimientos con barra', muscleGroup: MuscleGroup.ESPALDA, description: 'Básico de trapecio superior.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'trap-02', name: 'Encogimientos con mancuernas', muscleGroup: MuscleGroup.ESPALDA, description: 'Mayor libertad de movimiento para trapecios.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'trap-03', name: 'High pulls', muscleGroup: MuscleGroup.ESPALDA, description: 'Movimiento explosivo para potencia de hombros y trapecios.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'trap-04', name: 'Rack pulls', muscleGroup: MuscleGroup.ESPALDA, description: 'Peso muerto desde pines para enfoque en espalda alta.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'trap-05', name: 'Power shrugs', muscleGroup: MuscleGroup.ESPALDA, description: 'Encogimientos con ligero impulso de piernas para mayor carga.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- HOMBROS ---
  { id: 'push-01', name: 'Press militar', muscleGroup: MuscleGroup.HOMBROS, description: 'Fuerza vertical absoluta de hombros.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-02', name: 'Press con mancuernas', muscleGroup: MuscleGroup.HOMBROS, description: 'Empuje vertical con mayor rango y estabilidad.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-03', name: 'Elevaciones laterales', muscleGroup: MuscleGroup.HOMBROS, description: 'Clave para la anchura del hombro.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-04', name: 'Elevaciones frontales', muscleGroup: MuscleGroup.HOMBROS, description: 'Enfoque en el deltoides anterior.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-05', name: 'Pájaros', muscleGroup: MuscleGroup.HOMBROS, description: 'Enfoque en el deltoides posterior.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-06', name: 'Press Arnold', muscleGroup: MuscleGroup.HOMBROS, description: 'Variante rotacional para activación completa.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-07', name: 'Elevaciones posteriores', muscleGroup: MuscleGroup.HOMBROS, description: 'Aislamiento específico de la cara trasera del hombro.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-08', name: 'Remo al mentón', muscleGroup: MuscleGroup.HOMBROS, description: 'Trabajo híbrido de deltoides y trapecio.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-09', name: 'Elevaciones en polea', muscleGroup: MuscleGroup.HOMBROS, description: 'Tensión constante para el deltoides lateral.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-10', name: 'Y-raises', muscleGroup: MuscleGroup.HOMBROS, description: 'Excelente para salud escapular y deltoides lateral/posterior.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-11', name: 'Z-press', muscleGroup: MuscleGroup.HOMBROS, description: 'Press militar sentado en el suelo para máximo control del core.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-12', name: 'Pike push ups', muscleGroup: MuscleGroup.HOMBROS, description: 'Empuje vertical con peso corporal.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'push-13', name: 'Handstand push ups', muscleGroup: MuscleGroup.HOMBROS, description: 'Fuerza extrema de hombros en vertical invertida.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- BRAZOS ---
  { id: 'arm-01', name: 'Curl con barra', muscleGroup: MuscleGroup.BRAZOS, description: 'Básico constructor de masa en bíceps.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-02', name: 'Curl con mancuernas', muscleGroup: MuscleGroup.BRAZOS, description: 'Permite supinación completa para el pico del bíceps.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-03', name: 'Curl alterno', muscleGroup: MuscleGroup.BRAZOS, description: 'Fuerza unilateral y concentración en cada brazo.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-04', name: 'Curl martillo', muscleGroup: MuscleGroup.BRAZOS, description: 'Enfoque en braquiorradial y braquial anterior.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-05', name: 'Curl concentrado', muscleGroup: MuscleGroup.BRAZOS, description: 'Máximo aislamiento evitando el balanceo.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-06', name: 'Curl predicador', muscleGroup: MuscleGroup.BRAZOS, description: 'Aísla el bíceps eliminando la ayuda de los hombros.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-07', name: 'Curl en polea', muscleGroup: MuscleGroup.BRAZOS, description: 'Tensión constante durante todo el recorrido.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-08', name: 'Curl 21', muscleGroup: MuscleGroup.BRAZOS, description: 'Método de fatiga intensiva dividiendo el rango de movimiento.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-09', name: 'Curl araña', muscleGroup: MuscleGroup.BRAZOS, description: 'Enfoque en la cabeza corta del bíceps.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-10', name: 'Curl inclinado', muscleGroup: MuscleGroup.BRAZOS, description: 'Máximo estiramiento de la cabeza larga del bíceps.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-11', name: 'Fondos en banco', muscleGroup: MuscleGroup.BRAZOS, description: 'Tríceps con peso corporal o lastre.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-12', name: 'Press francés', muscleGroup: MuscleGroup.BRAZOS, description: 'Básico de potencia para el tríceps.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-13', name: 'Extensión en polea', muscleGroup: MuscleGroup.BRAZOS, description: 'Tensión mecánica constante para tríceps.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-14', name: 'Patada de tríceps', muscleGroup: MuscleGroup.BRAZOS, description: 'Enfoque en la contracción máxima del tríceps.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'arm-15', name: 'Skull crushers', muscleGroup: MuscleGroup.BRAZOS, description: 'Extensión de codo explosiva y potente.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- AGARRE ---
  { id: 'grip-01', name: 'Curl de muñeca', muscleGroup: MuscleGroup.AGARRE, description: 'Fortalecimiento de los flexores del antebrazo.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'grip-02', name: 'Curl inverso', muscleGroup: MuscleGroup.AGARRE, description: 'Fortalecimiento de los extensores y braquiorradial.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'grip-03', name: 'Farmer walk', muscleGroup: MuscleGroup.AGARRE, description: 'Paseo del granjero para agarre isométrico y core.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.TIME_WEIGHT, ...INITIAL_PROGRESS },
  { id: 'grip-04', name: 'Dead hang', muscleGroup: MuscleGroup.AGARRE, description: 'Colgarse para máxima resistencia de agarre.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'grip-05', name: 'Wrist roller', muscleGroup: MuscleGroup.AGARRE, description: 'Rodillo de muñeca para fatiga extrema de antebrazo.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'grip-06', name: 'Pinch grip', muscleGroup: MuscleGroup.AGARRE, description: 'Fuerza de pinza con discos.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },

  // --- PIERNAS ---
  { id: 'leg-01', name: 'Sentadilla', muscleGroup: MuscleGroup.PIERNAS, description: 'Básico absoluto del tren inferior.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-02', name: 'Prensa', muscleGroup: MuscleGroup.PIERNAS, description: 'Empuje de piernas con grandes cargas.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-03', name: 'Sentadilla búlgara', muscleGroup: MuscleGroup.PIERNAS, description: 'Unilateral extremo para cuádriceps y glúteo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-04', name: 'Gemelos de pie', muscleGroup: MuscleGroup.PIERNAS, description: 'Aislamiento del gastrocnemio.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-05', name: 'Step ups', muscleGroup: MuscleGroup.PIERNAS, description: 'Subidas al cajón para fuerza funcional.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-06', name: 'Curl femoral', muscleGroup: MuscleGroup.PIERNAS, description: 'Aislamiento de la parte posterior del muslo.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-07', name: 'Extensión de cuádriceps', muscleGroup: MuscleGroup.PIERNAS, description: 'Aislamiento del cuádriceps en máquina.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-08', name: 'Jump squats', muscleGroup: MuscleGroup.PIERNAS, description: 'Potencia pliométrica explosiva.', rankArchetype: RankArchetype.COMBAT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-09', name: 'Box jumps', muscleGroup: MuscleGroup.PIERNAS, description: 'Saltos al cajón para explosividad.', rankArchetype: RankArchetype.COMBAT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-10', name: 'Sprint', muscleGroup: MuscleGroup.PIERNAS, description: 'Carrera de máxima intensidad.', rankArchetype: RankArchetype.ENDURANCE, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },

  // --- CORE & CUELLO ---
  { id: 'core-01', name: 'Plancha', muscleGroup: MuscleGroup.CORE, description: 'Isométrico fundamental de estabilidad.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'core-02', name: 'Hollow hold', muscleGroup: MuscleGroup.CORE, description: 'Estabilidad avanzada estilo gimnasia.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'core-03', name: 'Flexión cervical', muscleGroup: MuscleGroup.CORE, description: 'Fortalecimiento de la parte anterior del cuello.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'core-04', name: 'Extensión cervical', muscleGroup: MuscleGroup.CORE, description: 'Fortalecimiento de la parte posterior del cuello.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'core-05', name: 'Rotaciones cervicales', muscleGroup: MuscleGroup.CORE, description: 'Movilidad y fuerza rotacional del cuello.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- FULL BODY ---
  { id: 'fb-01', name: 'Snatch (Arrancada)', muscleGroup: MuscleGroup.FULL_BODY, description: 'Potencia explosiva máxima olímpica.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'fb-02', name: 'Power clean', muscleGroup: MuscleGroup.FULL_BODY, description: 'Transferencia de fuerza explosiva desde el suelo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- ABDOMEN ---
  { id: 'abd-01', name: 'Crunch', muscleGroup: MuscleGroup.ABDOMEN, description: 'Flexión abdominal básica para el recto abdominal.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-02', name: 'Crunch en máquina', muscleGroup: MuscleGroup.ABDOMEN, description: 'Crunch asistido con carga mecánica.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-03', name: 'Crunch con polea', muscleGroup: MuscleGroup.ABDOMEN, description: 'Excelente para añadir carga progresiva al abdomen.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-04', name: 'Elevaciones de piernas colgado', muscleGroup: MuscleGroup.ABDOMEN, description: 'Gran demanda de la porción inferior del abdomen y agarre.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-05', name: 'Elevaciones de piernas en banco', muscleGroup: MuscleGroup.ABDOMEN, description: 'Versión controlada para estabilidad lumbar y abdominal.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-06', name: 'Ab wheel', muscleGroup: MuscleGroup.ABDOMEN, description: 'Extensión abdominal de alta intensidad.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-07', name: 'Plancha lateral', muscleGroup: MuscleGroup.ABDOMEN, description: 'Enfoque en oblicuos y estabilidad lateral.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'abd-08', name: 'Mountain climbers', muscleGroup: MuscleGroup.ABDOMEN, description: 'Ejercicio dinámico de core y cardio.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-09', name: 'Russian twist', muscleGroup: MuscleGroup.ABDOMEN, description: 'Fuerza rotacional para oblicuos.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-10', name: 'Bicicleta abdominal', muscleGroup: MuscleGroup.ABDOMEN, description: 'Coordinación y tensión oblicua constante.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-11', name: 'Sit ups', muscleGroup: MuscleGroup.ABDOMEN, description: 'Flexión de tronco completa clásica.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-12', name: 'V ups', muscleGroup: MuscleGroup.ABDOMEN, description: 'Flexión simultánea de tronco y piernas.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-13', name: 'Toes to bar', muscleGroup: MuscleGroup.ABDOMEN, description: 'Movimiento de gimnasia avanzado para core total.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-14', name: 'Dead bug', muscleGroup: MuscleGroup.ABDOMEN, description: 'Control motor y estabilidad lumbopélvica profunda.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-15', name: 'Dragon flag', muscleGroup: MuscleGroup.ABDOMEN, description: 'El pináculo del control corporal abdominal.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'abd-16', name: 'Windshield wipers', muscleGroup: MuscleGroup.ABDOMEN, description: 'Control rotacional extremo colgado.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- PANTORRILLAS (Adicionales) ---
  { id: 'leg-11', name: 'Elevación de talones sentado', muscleGroup: MuscleGroup.PIERNAS, description: 'Enfoque en el músculo sóleo.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-12', name: 'Pantorrillas en prensa', muscleGroup: MuscleGroup.PIERNAS, description: 'Permite manejar grandes cargas con seguridad.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-13', name: 'Saltos de pantorrilla', muscleGroup: MuscleGroup.PIERNAS, description: 'Fuerza reactiva y potencia elástica.', rankArchetype: RankArchetype.COMBAT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-14', name: 'Skipping', muscleGroup: MuscleGroup.PIERNAS, description: 'Potencia de zancada y resistencia específica.', rankArchetype: RankArchetype.ENDURANCE, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },
  { id: 'leg-15', name: 'Pantorrillas con mancuerna', muscleGroup: MuscleGroup.PIERNAS, description: 'Variante unilateral para equilibrio de fuerza.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-16', name: 'Pantorrillas en escalón', muscleGroup: MuscleGroup.PIERNAS, description: 'Aumenta el rango de estiramiento del tendón.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-17', name: 'Donkey calf raises', muscleGroup: MuscleGroup.PIERNAS, description: 'Estiramiento máximo del gastrocnemio bajo carga.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'leg-18', name: 'Farmer calf raises', muscleGroup: MuscleGroup.PIERNAS, description: 'Caminata en puntas para resistencia de agarre y gemelo.', rankArchetype: RankArchetype.ENDURANCE, metricType: ExerciseMetric.TIME, ...INITIAL_PROGRESS },

  // --- GLÚTEO ---
  { id: 'glu-01', name: 'Hip thrust', muscleGroup: MuscleGroup.PIERNAS, description: 'Ejercicio rey para la extensión de cadera y masa del glúteo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'glu-02', name: 'Puente de glúteo', muscleGroup: MuscleGroup.PIERNAS, description: 'Activación y estabilidad de la cadena posterior.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'glu-03', name: 'Patada de glúteo en polea', muscleGroup: MuscleGroup.PIERNAS, description: 'Aislamiento máximo de la extensión de cadera.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'glu-04', name: 'Abducción de cadera en máquina', muscleGroup: MuscleGroup.PIERNAS, description: 'Fortalecimiento del glúteo medio y estabilidad lateral.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'glu-05', name: 'Abducción con banda elástica', muscleGroup: MuscleGroup.PIERNAS, description: 'Tensión constante para salud de cadera.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'glu-06', name: 'Step up alto', muscleGroup: MuscleGroup.PIERNAS, description: 'Fuerza funcional y reclutamiento máximo de glúteo.', rankArchetype: RankArchetype.BODYWEIGHT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'glu-07', name: 'Sentadilla sumo', muscleGroup: MuscleGroup.PIERNAS, description: 'Variante abierta para énfasis en aductores y glúteo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'glu-08', name: 'Zancadas largas', muscleGroup: MuscleGroup.PIERNAS, description: 'Énfasis en el estiramiento y potencia del glúteo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },

  // --- EJERCICIOS ESPECIALES ---
  { id: 'spec-01', name: 'Halos de hombro a hombro', muscleGroup: MuscleGroup.HOMBROS, description: 'Movilidad y estabilidad circular del hombro.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-02', name: 'Halos con disco', muscleGroup: MuscleGroup.HOMBROS, description: 'Control de core y movilidad torácica circular.', rankArchetype: RankArchetype.ISOLATION, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-03', name: 'Halo con kettlebell', muscleGroup: MuscleGroup.HOMBROS, description: 'Fuerza de estabilización con peso descentrado.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-04', name: 'Jalón en polea de judo', muscleGroup: MuscleGroup.ESPALDA, description: 'Tracción técnica enfocada en deportes de agarre.', rankArchetype: RankArchetype.COMBAT, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-05', name: 'Remo en T con agarre neutro', muscleGroup: MuscleGroup.ESPALDA, description: 'Grosor de espalda media con posición segura de hombros.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-06', name: 'Press de hombro con mancuernas alternadas', muscleGroup: MuscleGroup.HOMBROS, description: 'Control unilateral y tiempo bajo tensión aumentado.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-07', name: 'Press de pecho con mancuernas alternadas', muscleGroup: MuscleGroup.PECHO, description: 'Estabilidad de core y tracción pectoral unilateral.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-08', name: 'Remo foca', muscleGroup: MuscleGroup.ESPALDA, description: 'Remo horizontal puro eliminando el impulso del cuerpo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-09', name: 'Press landmine', muscleGroup: MuscleGroup.HOMBROS, description: 'Empuje diagonal excelente para salud de hombro y potencia.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-10', name: 'Landmine press', muscleGroup: MuscleGroup.HOMBROS, description: 'Variante de empuje con trayectoria de arco para estabilidad.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS },
  { id: 'spec-11', name: 'Clean', muscleGroup: MuscleGroup.FULL_BODY, description: 'Movimiento de potencia olímpica completo.', rankArchetype: RankArchetype.STRENGTH, metricType: ExerciseMetric.REPS, ...INITIAL_PROGRESS }
];
